services:
  - type: web
    name: flightgo-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: RAPIDAPI_KEY
        value: K0DIojlrT0msh940ger0Im41erhUp1fFCItjsnuAmYu1JTWoHm
      - key: FRONTEND_ORIGIN
        value: https://twdengwei.github.io
    healthCheckPath: /health
